# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
np.__version__

'1.26.4'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [10]:
### [your code here]
a = np.random.random((2, 3, 5))
a2 = np.random.rand(2, 3, 5)
a3 = np.random.randn(2, 3, 5)


### 4. Print a.


In [7]:
### [your code here]
print(a)

[[[5.62423571e-01 8.18312558e-01 4.76092020e-02 8.01574023e-01
   5.10236022e-01]
  [7.07721298e-01 9.53005556e-01 5.63375902e-01 7.09106679e-01
   4.23994214e-01]
  [8.65224030e-01 6.99652418e-01 5.72557871e-01 4.57245377e-04
   6.10327360e-01]]

 [[8.74537161e-01 9.18606362e-01 8.17248745e-01 4.04086835e-02
   6.49939117e-01]
  [7.03813168e-01 7.36547803e-03 4.76672046e-01 6.37021959e-01
   9.85890604e-01]
  [2.43304679e-01 6.61411206e-01 5.49272701e-01 6.63098200e-01
   2.15925209e-01]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [9]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
### [your code here]
total_elements_a = a.size
total_elements_b = b.size
same_size = total_elements_a == total_elements_b

print(f"Array a total elements: {total_elements_a}")
print(f"Array b total elements: {total_elements_b}")
print(f"Do a and b have the same number of elements? {same_size}")

Array a total elements: 30
Array b total elements: 30
Do a and b have the same number of elements? True



### 8. Are you able to add a and b? Why or why not?


In [12]:
### [your code here]
try:
    sum_of_a_b = a + b
except ValueError as e:
    print(f"Error: {e}")

Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [14]:
### [your code here]
c = b.transpose(1, 2, 0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [19]:
### [your code here]

try:
    d = a + c
    print(d)
except ValueError as e:
    print(f"Error: {e}")

[[[1.32390999 1.41345843 1.69502786 1.9917908  1.80407933]
  [1.66384884 1.51761612 1.5302965  1.35513148 1.94830687]
  [1.48519849 1.7759716  1.02051551 1.74549151 1.73272023]]

 [[1.45254998 1.09302841 1.28597956 1.14710923 1.17547163]
  [1.90178872 1.81578756 1.16314141 1.60833701 1.95950749]
  [1.78962359 1.41674694 1.48719084 1.09713034 1.49630455]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [20]:
### [your code here]
print(a)
print(d)


[[[0.32390999 0.41345843 0.69502786 0.9917908  0.80407933]
  [0.66384884 0.51761612 0.5302965  0.35513148 0.94830687]
  [0.48519849 0.7759716  0.02051551 0.74549151 0.73272023]]

 [[0.45254998 0.09302841 0.28597956 0.14710923 0.17547163]
  [0.90178872 0.81578756 0.16314141 0.60833701 0.95950749]
  [0.78962359 0.41674694 0.48719084 0.09713034 0.49630455]]]
[[[1.32390999 1.41345843 1.69502786 1.9917908  1.80407933]
  [1.66384884 1.51761612 1.5302965  1.35513148 1.94830687]
  [1.48519849 1.7759716  1.02051551 1.74549151 1.73272023]]

 [[1.45254998 1.09302841 1.28597956 1.14710923 1.17547163]
  [1.90178872 1.81578756 1.16314141 1.60833701 1.95950749]
  [1.78962359 1.41674694 1.48719084 1.09713034 1.49630455]]]



### 12. Multiply a and c. Assign the result to e.


In [21]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [31]:
### [your code here]
print(e == a)


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [28]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f"Max: {d_max}")
print(f"Min: {d_min}")
print(f"Mean: {d_mean}")


Max: 1.991790796882525
Min: 1.0205155094520564
Mean: 1.5297686931980106



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [26]:
### [your code here]
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [29]:
### [your code here]
# Assign 0 to f where d equals d_min
f[d == d_min] = 0

# Assign 100 to f where d equals d_max
f[d == d_max] = 100

# Assign 50 to f where d equals d_mean
f[d == d_mean] = 50

# Assign 25 to f where d is larger than d_min AND smaller than d_mean
f[(d > d_min) & (d < d_mean)] = 25

# Assign 75 to f where d is larger than d_mean AND smaller than d_max
f[(d > d_mean) & (d < d_max)] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [30]:
### [your code here]
print(d)
print(f)

[[[1.32390999 1.41345843 1.69502786 1.9917908  1.80407933]
  [1.66384884 1.51761612 1.5302965  1.35513148 1.94830687]
  [1.48519849 1.7759716  1.02051551 1.74549151 1.73272023]]

 [[1.45254998 1.09302841 1.28597956 1.14710923 1.17547163]
  [1.90178872 1.81578756 1.16314141 1.60833701 1.95950749]
  [1.78962359 1.41674694 1.48719084 1.09713034 1.49630455]]]
[[[ 25.  25.  75. 100.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.   0.  75.  75.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25.  25.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [35]:
### [your code here]
f = np.empty(d.shape, dtype='<U1')

f[d == d_min] = "A"

# Assign "E" to f where d equals d_max
f[d == d_max] = "E"

# Assign "C" to f where d equals d_mean
f[d == d_mean] = "C"

# Assign "D" to f where d is larger than d_min AND smaller than d_mean
f[(d > d_min) & (d < d_mean)] = "D"

# Assign "B" to f where d is larger than d_mean AND smaller than d_max
f[(d > d_mean) & (d < d_max)] = "B"

print(f)

[[['D' 'D' 'B' 'E' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['D' 'B' 'A' 'B' 'B']]

 [['D' 'D' 'D' 'D' 'D']
  ['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'D' 'D']]]
